### PR TITLE
Fixes ACL's with spaces

### PR DESCRIPTION
**Pull request by i1tech**
Fix for ACL's with spaces, which otherwise cause ACL's to be applied with every puppet agent run.

### CODE REVIEW

**Comment by dobbymoodge** [comment]
@i1tech Sorry for the slow response, can you update the tests to cover this functionality?

**Comment by dobbymoodge** [comment]
Also, when can ACLs have spaces in them?

**Comment by i1tech** [comment]
Spaces in ACL's are common when Auth'ing against an Active Directory Domain controller, especially in the case of Groups.  (ie "Domain Adminsitrators", "Service Accounts", etc)  Depending on how the Linux side is setup, using SSS, LDAP, NSLCD+LDAP, Winbind, LikewiseOpen, Centrify, etc. you will also find spaces embedded in the username. I'll try to find some time to work on the tests.

**Comment by dobbymoodge** [comment]
@i1tech Also, please rebase so Travis stops whining about Ruby 1.8.7. :D

**Comment by roidelapluie** [comment]
@dobbymoodge you have push access to the repo .. that is a new github feature

**Comment by dobbymoodge** [comment]
@roidelapluie ah, so I do. Now I understand what you were going on about. ☺️

**Comment by dobbymoodge** [comment]
@roidelapluie @i1tech I added a test, but I'm not sure I did it the **_Right Way_**. In particular, I wonder if I should be able to stub out the 2 methods without pulling in `RSpec::Mocks`. Thoughts?

**Comment by i1tech** [comment]
Thanks for adding that test, it would probably have been a while before I was able to get to it. Seem very busy these days.

**Comment by dobbymoodge** [comment]
@i1tech You've actually tested this in an environment with spaces in the group/usernames?

**Comment by dobbymoodge** [comment]
Waiting for feedback from @roidelapluie on the quality of this test before I merge. :)

**Comment by i1tech** [comment]
Absolutely, we are running the patched version of the module on our Puppet4 server.

**Comment by dobbymoodge** [comment]
I'll go ahead and merge then, and we can fix the test later if needed.

**Pull request merged**
