### PR TITLE
Add the Puppetlabs Skeleton for testing

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
https://travis-ci.org/Inuits/puppet-acl/jobs/74443320

**Comment by dobbymoodge** [comment]
@roidelapluie This is just the testing boilerplate without any actual tests, right?

**Comment by roidelapluie** [comment]
It already check of the ruby code is compatible with each ruby version. But there are not further tests.

it also checks the metatada.json file.

**Comment by dobbymoodge** [comment]
I'll try to test this tonight or tomorrow if I can find time, then merge. Thanks!

**Comment by roidelapluie** [comment]
Thanks!

**Comment by roidelapluie** [comment]
@dobbymoodge I have added actual tests now

**Comment by roidelapluie** [comment]
See the result here: https://travis-ci.org/Inuits/puppet-acl/builds/74559707

**Comment by roidelapluie** [comment]
Please note that you wiil need to register this repo on travis-ci.org

**Comment by roidelapluie** [comment]
@dobbymoodge Did you give it a try?

**Comment by roidelapluie** [comment]
FYI I have also sent this to the puppet users mailing list: https://groups.google.com/forum/?hl=fr#!topic/puppet-users/t4FNvLdfz7o Any idea is welcome

**Comment by dobbymoodge** [comment]
@roidelapluie I haven't had a chance to look at this yet; I'll try to set aside some time tomorrow. Sorry for the delay - this isn't part of my work focus anymore so it's hard to allocate time to it consistently.

**Comment by dobbymoodge** [comment]
@roidelapluie Sorry for the slow merge

**Pull request merged**
