### PR TITLE
Add autorequire on parent ACL

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by dobbymoodge** [comment]
I can't determine that this behaves any differently from what's already in master. What is really needed (and what I haven't figured out how to do yet) is to make an `Acl` for a directory require `File`s that are **children** of the directory. So for example, given these`File`s:
```puppet
file { "/tmp/testdir":
    ensure => directory,
    owner => blah,
    group => blah,
}

file { "/tmp/testdir/b":
    ensure => file,
    owner => blah,
    group => blah,
}

```
and this `Acl`:
```puppet
acl { "/tmp/testdir":
    action     => set,
    permission => [
                   "user::rwx",
                   "group::---",
                   "mask::r-x",
                   "other::---",
                   "default:user::rwx",
                   "default:group::r-x",
                   "default:mask::rwx",
                   "default:other::---",
                   ],
    provider   => posixacl,
    recursive  => true,
    recursemode => deep,
}
```
the `Acl` should require **both** of the `File` resources, since `/tmp/testdir/b` will (probably) be created **after** the `Acl` is applied to `/tmp/testdir`, and so `/tmp/testdir/b` will have the ACLs that are calculated at file create (`mask::rw-, user::rw-`) instead of the ACLs that are intended to be applied (`mask::rwx, user::rwx`).

I'm not sure how to do this.

**Comment by roidelapluie** [comment]
@dobbymoodge done

**Comment by dobbymoodge** [comment]
This doesn't work because it looks for the additional requirements in the filesystem instead of in the catalog. Also, I haven't been able to get it to work (under ruby 1.8.7).

**Comment by roidelapluie** [comment]
what about this

**Comment by dobbymoodge** [comment]
@roidelapluie I'll have to test it again tomorrow, but at first glance it isn't handling the test case outlined above. I'm out of time today, unfortunately.

**Comment by dobbymoodge** [comment]
@roidelapluie At least with the `test.pp` file I listed above, this still requires 2 runs before the final calculated ACLs are applied to `/tmp/testdir/a`. I wonder if we're trying to solve the same problem? I would really love to see the `Acl` resources applied only after all the `File` resources which are interdependent with the `Acl` are applied.

Maybe it's possible to force the `Acl` resources to only get applied after every `File` resource is applied? Or are the `Acl` autorequires unsatisfied because the interdependent `File` paths don't exist at the time the catalog is compiled? If that's the case, then maybe the only way to avoid multiple runs for nested ACLs is to implement https://github.com/dobbymoodge/puppet-acl/issues/16

**Comment by roidelapluie** [comment]
I know the problem now. Quickly taking a look.

**Comment by roidelapluie** [comment]
now it should be fine

**Comment by roidelapluie** [comment]
it is not good yet

**Comment by roidelapluie** [comment]
Now it should be ok

**Pull request merged**
